

package libreria;

/**
 * 
 * Classe che implementa un frame che visualizza messaggi di avviso relativi ad un evento specifico.
 * 
 * @author Giuseppe
 * @author Calogero
 * @author Marco
 */

public class NotificaFrame extends javax.swing.JFrame {

    /**
     * Costruttore.
     * Crea un Frame.
     * @param messaggio -> messaggio da visualizzare all'interno del Frame
     * @param parent ->
     * @param modal ->
     */
    public NotificaFrame(String messaggio,java.awt.Frame parent, boolean modal) {
        initComponents();
        JLabelMessaggio.setText(messaggio);
        setLocationRelativeTo(null);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelMessaggio = new javax.swing.JLabel();
        JButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelMessaggio.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        JLabelMessaggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelMessaggio.setText("jLabel1");

        JButtonOk.setText("OK");
        JButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(JButtonOk)
                .addContainerGap(121, Short.MAX_VALUE))
            .addComponent(JLabelMessaggio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(JLabelMessaggio)
                .addGap(18, 18, 18)
                .addComponent(JButtonOk)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Metodo che chiude la finestra di dialogo dopo avere premuto il bottoneOK
 * @param evt -> pressione su JButtonOk
 */
    private void JButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButtonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonOk;
    private javax.swing.JLabel JLabelMessaggio;
    // End of variables declaration//GEN-END:variables
}
