
package libreria;

import javax.swing.SwingUtilities;

/**
 * 
 * Classe che implementa un Frame che mostra tutte le informazioni relative a ogni elemento contenuto all'interno della libreria.
 * in base al tipo (MP3/MP4/PDF) dell'elemento di cui si desidera visualizzare le informazioni vengono mostrate informazioni diverse.
 * 
 * @author Giuseppe
 * @author Calogero
 * @author Marco
 */

public class VisualizzaInformazioni extends javax.swing.JFrame {
    /**
     * VARIABILI.
     * 
     * -elemento -> elemento di cui si visualizzano le informazioni.
     * -modelloTabella -> istanza della classe MyTableModel che fornisce la struttura grafica della tabella per la visualizzazione degli elementi
     *                    della libreria.
     * -lib -> libreria da dove viene estratto l'elemento di cui si voglioni visualizzare le informazioni.
     * -pos -> posizione dell'elemento all'interno della libreria
     */
    private Elemento elemento = null; 
    private MyTableModel modelloTabella;
    private MyLibreria lib;
    private int pos;

    /**
     * Creates new form VisualizzaInformazioni
     * @param lib
     * @param pos
     * @param modello
     */
    public VisualizzaInformazioni(MyLibreria lib, int pos, MyTableModel modello) {
        setLocationRelativeTo(null);
        this.lib=lib;
        this.pos=pos;
        this.elemento=lib.get(pos);
        this.modelloTabella=modello;
        
        initComponents();
        jLabelFrequenza.setVisible(false);
        jTextFrequenza.setVisible(false);
        checkboxSalva.setEnabled(false);
       
        
        switch (elemento.getTipo()){
            case "MP3": 
                jLabelFrequenza.setVisible(true);
                jTextFrequenza.setVisible(true);
                jLabelA.setText("Durata"); 
                BranoMusicale BN = (BranoMusicale)elemento; 
                JTextA.setText(BN.getDurata());
                jTextFrequenza.setText(BN.getFrequenza());       
                break;
                
            case "MP4": jLabelA.setText("Durata"); Video V = (Video)elemento; JTextA.setText(V.getDurata()); break;
            case "PDF": jLabelA.setText("N°Pagine"); EBook E = (EBook)elemento; JTextA.setText(E.getNPagine()); break;
        }
        JTextTitolo.setText(elemento.getTitolo());
        JTextAutore.setText(elemento.getAutore());
        JTextPercorso.setText(elemento.getPercorso());
        JTextAnno.setText(elemento.getAnno());
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitolo = new javax.swing.JLabel();
        jLabelAutore = new javax.swing.JLabel();
        jLabelFile = new javax.swing.JLabel();
        jLabelAnno = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        JTextTitolo = new javax.swing.JTextField();
        JTextAutore = new javax.swing.JTextField();
        JTextPercorso = new javax.swing.JTextField();
        JTextAnno = new javax.swing.JTextField();
        JTextA = new javax.swing.JTextField();
        JButtonModifica = new javax.swing.JButton();
        JButtonConferma = new javax.swing.JButton();
        checkboxSalva = new java.awt.Checkbox();
        jLabelFrequenza = new javax.swing.JLabel();
        jTextFrequenza = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitolo.setText("Titolo");

        jLabelAutore.setText("Autore");

        jLabelFile.setText("File ");

        jLabelAnno.setText("Anno");

        jLabelA.setText("Durata");

        JTextTitolo.setEditable(false);
        JTextTitolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextTitoloActionPerformed(evt);
            }
        });

        JTextAutore.setEditable(false);

        JTextPercorso.setEditable(false);

        JTextAnno.setEditable(false);

        JTextA.setEditable(false);

        JButtonModifica.setText("Modifica");
        JButtonModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonModificaActionPerformed(evt);
            }
        });

        JButtonConferma.setText("Conferma");
        JButtonConferma.setEnabled(false);
        JButtonConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConfermaActionPerformed(evt);
            }
        });

        checkboxSalva.setLabel("Salva");
        checkboxSalva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxSalvaMouseClicked(evt);
            }
        });

        jLabelFrequenza.setText("Frequenza");

        jTextFrequenza.setEditable(false);
        jTextFrequenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFrequenzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelFrequenza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFrequenza, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAutore)
                            .addComponent(jLabelFile)
                            .addComponent(jLabelAnno)
                            .addComponent(jLabelA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextTitolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextAutore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextPercorso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextAnno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonModifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(JButtonConferma)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkboxSalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkboxSalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitolo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextAutore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAutore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextPercorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelA)
                            .addComponent(JTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFrequenza)
                    .addComponent(jTextFrequenza, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonModifica)
                    .addComponent(JButtonConferma))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo che gestisce le modifiche sulle JText dei campi.
     * Permette la modifica delle informazioni visualizzate relative ad un elemento
     * @param evt -> pressione su JButtonModifica
     */
    private void JButtonModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonModificaActionPerformed
        // TODO add your handling code here:
        checkboxSalva.setEnabled(true);
        JTextA.setEditable(false);
        jTextFrequenza.setEditable(false);
        JTextAnno.setEditable(true);
        JTextAutore.setEditable(true);
        JTextTitolo.setEditable(true);
        //jButton4.setEnabled(false);
        JButtonModifica.setEnabled(false);

    }//GEN-LAST:event_JButtonModificaActionPerformed

    /**
     * Metodo che salva le modifiche (se sono state effettuate) dell'elemento selezionato.
     * Salva le modifiche sull'elemento effettuate dall'utente 
     * @param evt -> pressione su JButtonConferma
     */
    private void JButtonConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConfermaActionPerformed
        // TODO add your handling code here:
        elemento.setAnno(JTextAnno.getText());
        elemento.setAutore(JTextAutore.getText());
        elemento.setTitolo(JTextTitolo.getText());
        modelloTabella.aggiorna();
        this.dispose(); 

    }//GEN-LAST:event_JButtonConfermaActionPerformed

    /**
     * Metodo che abilità il bottone Conferma per salvare le modifiche.
     * @param evt -> click su checkboxSalva
     */
    private void checkboxSalvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxSalvaMouseClicked
        // TODO add your handling code here:
        
        JButtonConferma.setEnabled(true);
        
    }//GEN-LAST:event_checkboxSalvaMouseClicked

    private void JTextTitoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextTitoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextTitoloActionPerformed

    private void jTextFrequenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFrequenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFrequenzaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConferma;
    private javax.swing.JButton JButtonModifica;
    private javax.swing.JTextField JTextA;
    private javax.swing.JTextField JTextAnno;
    private javax.swing.JTextField JTextAutore;
    private javax.swing.JTextField JTextPercorso;
    private javax.swing.JTextField JTextTitolo;
    private java.awt.Checkbox checkboxSalva;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelAutore;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelFrequenza;
    private javax.swing.JLabel jLabelTitolo;
    private javax.swing.JTextField jTextFrequenza;
    // End of variables declaration//GEN-END:variables
}
